version: 1
labels:
  - label: "github"
    files:
      - ".github/.*"
      
  - label: "git"
    files:
      - ".gitignore"
      - ".gitattributes"
    
  - label: "docs"
    files:
      - "docs/.*"
      - "deliverables/.*"
      - "README.md"

  - label: "frontend-core"
    files:
      - "frontend/src/.*\\.ts$"

  - label: "frontend-ui"
    files:
      - "frontend/src/.*\\.tsx$"

  - label: "frontend-tests"
    files:
      - "frontend/test/.*"
  
  - label: "backend-core"
    files:
      - "backend/src/main/.*"

  - label: "backend-tests"
    files:
      - "backend/src/test/.*"
      
  - label: "xsmall-diff"
    size-below: 10
    
  - label: "small-diff"
    size-above: 9
    size-below: 100
    
  - label: "medium-diff"
    size-above: 99
    size-below: 500
    
  - label: "large-diff"
    size-above: 499
    size-below: 1000
    
  - label: "xlarge-diff"
    size-above: 999