services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  backend:
    build:
      context: ./backend
      secrets:
        - sentry_token
    restart: always
    ports:
      - "127.0.0.1:8082:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SENTRY_AUTO_INIT=false
      - DB_HOST=postgres
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    depends_on:
      - postgres
  frontend:
    build: ./frontend
    restart: always
    ports:
      - "127.0.0.1:8081:80"
    depends_on:
      - backend
volumes:
  pgdata:
secrets:
  sentry_token:
    environment: SENTRY_AUTH_TOKEN